version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    image: node:18
    command: >
      sh -c "npm install --legacy-peer-deps --only=prod &&
             node dist/main/server.js --inspect=0.0.0.0:9222 --nolazy"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
